Space contact revamp
lnu-norge/lokaler.lnu.no pull request #108
Opened 2021-11-26 16:14 UTC by DanielJackson-Oslo

## Moves space contact under "How to book", like in Figma:

![image](https://user-images.githubusercontent.com/14905290/143607995-a79a7ac0-0f0d-4de6-8339-12583e8c3f35.png)

## Revamped SpaceContact#new 
![image](https://user-images.githubusercontent.com/14905290/143608058-46d03e5d-e92c-4bbf-82e2-76739a7e01b6.png)

## Revamped SpaceContact#show and #index: 

![image](https://user-images.githubusercontent.com/14905290/143608092-9c448a11-221a-4376-9113-250f1efbbc42.png)

2021-11-29 08:17 UTC, mathias234 requested changes
Etter en form får validerings error så er det ikke mulig å lokke den

2021-11-29 09:20 UTC, DanielJackson-Oslo commented
> Hvis du får validerings error på new formen så vil du ikke kunne lukke modalen.
> 
> Redigerings formen blir borte hvis du får validerings error

Takk! Will fix.

2021-12-03 08:35 UTC, DanielJackson-Oslo commented
Tok litt tid, men fikset nå!

Problemet var at turmo_frame_tag-en var satt til dom_id for @space_contact, og ikke en streng. Å sette den til en streng løste problemet. 

Jeg er usikker på hvorfor det ble et problem, men kanskje den endrer seg når den blir forsøkt lagret?

2021-12-03 12:21 UTC, mathias234 requested changes
![Peek 2021-12-03 13-20](https://user-images.githubusercontent.com/2104029/144601708-837c2f64-5e57-4cb3-9fa0-734c363ff5bc.gif)
Redigering fungerer fremdeles ikke

2021-12-03 12:27 UTC, DanielJackson-Oslo commented
> ![Peek 2021-12-03 13-20](https://user-images.githubusercontent.com/2104029/144601708-837c2f64-5e57-4cb3-9fa0-734c363ff5bc.gif) Redigering fungerer fremdeles ikke

🤦‍♂️ Takk for at du tester, og beklager at jeg ikke fanget det opp selv!

Er det noen enkel måte å teste disse tingene på i programmatiske tester?

2021-12-03 12:58 UTC, DanielJackson-Oslo commented
@mathias234 Vi prøver igjen!

2021-12-03 14:45 UTC, mathias234 approved these changes
LGTM!

Er ikke noe enkel måte å teste dette på uten å bruke feature(capybara) tester

2021-12-03 21:14 UTC, merged