Add the ability to delete images
lnu-norge/lokaler.lnu.no pull request #114
Opened 2021-12-02 13:59 UTC by mathias234

Denne introduserer en ny kontroller `SpaceImagesController` som vil ta seg av alt ansvart for bilder (inkl opplasting) og redigering i framtiden.

2021-12-03 08:44 UTC, DanielJackson-Oslo requested changes
Litt visuell jank på redigerings-knapp, og savner en prompt på slette-knappen, men ellers ser det veldig bra ut!

2021-12-03 08:44 UTC, DanielJackson-Oslo commented on app/views/space_images/show.html.erb
> +    <%= link_to "Delete", space_image_path(@space, image: image), method: :delete, class: "btn btn-danger" %>
Savner en "Are you sure?" her, som vi har på andre delete-knapper.

2021-12-03 08:44 UTC, DanielJackson-Oslo commented on app/views/spaces/show/_image_header_edit_button.html.erb
> +      <%= inline_svg_tag 'edit', class: "h-6 w-6  text-gray-700", alt: t('images.upload'), title:  t('images.upload') %>
Ser litt janky ut.

https://www.loom.com/share/c879895dd94b443ea08d0c0d95aca593

Om du vil. kan jeg prøve fikse det, eller du kan få kose med det selv ;)

2021-12-07 08:31 UTC, mathias234 commented on app/views/spaces/show/_image_header_edit_button.html.erb
> +      <%= inline_svg_tag 'edit', class: "h-6 w-6  text-gray-700", alt: t('images.upload'), title:  t('images.upload') %>
Tror jeg har fikset det nå

2021-12-07 09:55 UTC, DanielJackson-Oslo requested changes
Mye bedre!

Tre småplukk til jeg fant: 

- Er fortsatt en boks under boksen, se bilder
- Ikonet (blyanten) er fortsatt større en de andre ikonene rundt, og mye større enn de andre "edit"-ikonene
- Mangler oversettelse for Edit Images (la ikke merke til dette sist, men må jo ha gjort det da også!)

Alt dette er jo front-end pirkeri, så si fra om jeg skal ta en pass på det eller om du vil kose deg! 🎉

2021-12-07 09:55 UTC, DanielJackson-Oslo commented on app/views/spaces/show/_image_header_edit_button.html.erb
> +      <span class="text"><%= t('images.edit_images') %></span>
Ser ut til å mangle oversettelse: 

![image](https://user-images.githubusercontent.com/14905290/145006880-0635986b-ce52-42d5-b574-45a18da73d45.png)

2021-12-07 09:55 UTC, DanielJackson-Oslo commented on app/views/spaces/show/_image_header_edit_button.html.erb
> +  <%= label_tag :image, role: "button" do %>
Virker som label fortsatt "synes" under knappen når man hoverer. (Eller hva nå enn som er den boksen som kommer under her på bildet: 

![image](https://user-images.githubusercontent.com/14905290/145006969-9bc1bb16-76b8-44ea-9dee-ce3f4ce33e9e.png)

Usikker på hvordan fikse, men må jo gå an!

2021-12-07 11:48 UTC, DanielJackson-Oslo approved these changes
Ser bra ut!

2021-12-07 13:07 UTC, DanielJackson-Oslo commented
La akkurat merke til at ikonet på "Last opp bilde" blir veldig stort når det ikke er noe bilde lastet opp. 

Før så det sånn ut: 

![image](https://user-images.githubusercontent.com/14905290/145034608-e7ca3450-629b-43de-87e2-e4f0aa10b629.png)

Nå ser det sånn ut:

![image](https://user-images.githubusercontent.com/14905290/145034657-00ea55b5-0ce7-40c1-8f45-9435e1d2e3d3.png)

2021-12-07 13:21 UTC, mathias234 commented
> La akkurat merke til at ikonet på "Last opp bilde" blir veldig stort når det ikke er noe bilde lastet opp.
> 
> Før så det sånn ut:
> 
> ![image](https://user-images.githubusercontent.com/14905290/145034608-e7ca3450-629b-43de-87e2-e4f0aa10b629.png)
> 
> Nå ser det sånn ut:
> 
> ![image](https://user-images.githubusercontent.com/14905290/145034657-00ea55b5-0ce7-40c1-8f45-9435e1d2e3d3.png)

Ja blir sånn da jeg endret ikonet til å være mer synlig. Men tror dette er noe som må fikses når vi legger inn en bedre ikon pakke.

2021-12-07 15:40 UTC, merged