Notify on new review
lnu-norge/lokaler.lnu.no pull request #120
Opened 2021-12-06 12:19 UTC by DanielJackson-Oslo

Adds a flash message when writing a new review, as well as a test for that flash message. 

Also fixes so the reviews section is reloaded with the new review even if there were no reviews there already, fixing the bug in https://trello.com/c/85WKlQl9/178-live-stream-av-nye-reviews-til-spaceshow-oppdaterer-ikke-n%C3%A5r-de-g%C3%A5r-fra-0-1

2021-12-07 10:53 UTC, DanielJackson-Oslo commented on app/views/spaces/show/_reviews.html.erb
> +      space: @space
Trengs ikke sette local for @space , kan bare bruke den vi har

2021-12-15 16:14 UTC, DanielJackson-Oslo commented
@mathias234 Ready for review

2021-12-15 18:31 UTC, mathias234 requested changes
I don't seem to be getting a flash message. But the reviews section does get the new entry

2021-12-15 19:17 UTC, DanielJackson-Oslo commented
> I don't seem to be getting a flash message. But the reviews section does get the new entry

Hm... Will investigate. I even made a test for getting the flash message, so it might be faulty!

2021-12-15 19:22 UTC, DanielJackson-Oslo commented
Fikset! Hadde klart å fjerne elementet som turbo stream sendte til når jeg merget inn main sine endringer.

@mathias234 Noen idé om hvordan teste at turbo streams fungerer som de skal? Trenger vi capybara-tester for det?

2021-12-16 12:36 UTC, mathias234 approved these changes
LGTM! 
Begge fungere nye reviews kommer opp i listen og jeg får en flash message 🚀

2021-12-16 12:38 UTC, mathias234 commented
> @mathias234 Noen idé om hvordan teste at turbo streams fungerer som de skal? Trenger vi capybara-tester for det?

Har funnet en guide på hvordan vi kan teste turbo stream med en request spec, men har aldri prøvd det selv https://github.com/mdominiak/hotwire-chat#testing

2021-12-16 13:50 UTC, merged