Space group optional consequences
lnu-norge/lokaler.lnu.no pull request #128
Opened 2021-12-08 08:13 UTC by DanielJackson-Oslo

## Only lists out SpaceGroup information if there is a SpaceGroup set

So it now looks like this if SpaceGroup is nil:

![image](https://user-images.githubusercontent.com/14905290/145046927-e8f3fe19-dae6-4033-9a1d-e6d4fcafa7d6.png)

And like this if SpaceGroup is set: 
![image](https://user-images.githubusercontent.com/14905290/145047019-039278a8-ab5a-4036-b30c-f179c06ab56e.png)

## Changes the space group selection to a dropdown instead of TomSelect

So the user can easily select "nil":

![image](https://user-images.githubusercontent.com/14905290/145046830-6970280c-4d8d-44d1-9e7d-c7ea29a9f206.png)

Also changes the naming to reflect the move from SpaceOwner to SpaceGroup.

If user has a SpaceGroup it looks like this:

![image](https://user-images.githubusercontent.com/14905290/145046678-85d5efc6-0469-4753-88ff-700ebc42ef76.png)

## Temporarily removes ability to quickly add SpaceGroups from the Space#basics form

An unfortunate consequence of TomSelect going out for the field is that we have lost the ability to add a new SpaceGroup on the fly. The previous implementation wasn't testing well either, so I want to I want to do it differently this time and rethink the UX to be a more standard combination of (searchable) dropdown + "add new" button, perhaps like this: 

![image](https://user-images.githubusercontent.com/14905290/145172430-d768b4c0-b7e4-4c3b-9bec-989c4af2b084.png)

Hopefully I can find a gem for that, if not I'll make a pass at a simple implementation.

2021-12-08 08:23 UTC, DanielJackson-Oslo commented
Just found out that TomSelect can do what I want! Making a change back to TomSelect with some changes :)

2021-12-15 16:00 UTC, DanielJackson-Oslo commented on app/javascript/controllers/index.js
> -import MultiselectController from "./multiselect_controller"
Replaced by TomSelectController

2021-12-15 16:00 UTC, DanielJackson-Oslo commented on app/javascript/controllers/locationsearch_controller.js
> -import "../../javascript/stylesheets/tom-select.css"
Moved to SASS files

2021-12-15 16:01 UTC, DanielJackson-Oslo commented on app/javascript/controllers/tom_select_controller.js
> +        "dropdown": {
Makes it possible to create variants like "dropdown" that have the same configurations for all variants.

2021-12-15 18:39 UTC, mathias234 requested changes
Looks like we are getting an error when selecting the option to add a new space group.

![new space group](https://user-images.githubusercontent.com/2104029/146245642-85fd9a6d-acb0-4d1e-b368-84297cd0876e.gif)

2021-12-15 19:24 UTC, DanielJackson-Oslo commented
> Looks like we are getting an error when selecting the option to add a new space group.
> 
> ![new space group](https://user-images.githubusercontent.com/2104029/146245642-85fd9a6d-acb0-4d1e-b368-84297cd0876e.gif)

😬  SÅ mye for å teste happy-path for man sender inn PR! Takk for at du fant, skal fikse.

2021-12-16 08:07 UTC, DanielJackson-Oslo commented
@mathias234 Tror jeg har fikset det nå!

Ikke fått laget en test på det, for vet ikke helt hvordan teste form behaviour. Vet at Ole har snakket om at vi kanskje burde hatt capybara-tester på prosjekter her allikevel, og merker at jeg er litt enig med ham... Hva tror du?

2021-12-16 12:29 UTC, mathias234 commented
> @mathias234 Tror jeg har fikset det nå!
> 
> Ikke fått laget en test på det, for vet ikke helt hvordan teste form behaviour. Vet at Ole har snakket om at vi kanskje burde hatt capybara-tester på prosjekter her allikevel, og merker at jeg er litt enig med ham... Hva tror du?

Er enig, vi har en veldig tung frontend hvor ting lett kan gå galt. Jeg kan skrive noen I dag så kan vi se hvordan det blir

2021-12-16 12:33 UTC, mathias234 approved these changes

2021-12-16 13:50 UTC, merged