Add caption credits
lnu-norge/lokaler.lnu.no pull request #130
Opened 2021-12-09 13:04 UTC by mathias234

Adds captions & credits to images

![image](https://user-images.githubusercontent.com/2104029/145401549-888dbdd7-f1f5-4d76-8a0f-652e98a302e7.png)

This required adding a new model to hold the caption and credits and I have not written any migration for converting from the old  to the new so images will have to be re-uploaded.

2021-12-09 13:16 UTC, mathias234 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Caption og kreditering på bilder.](https://trello.com/c/rFmDAkuW/193-caption-og-kreditering-p%C3%A5-bilder)

2021-12-11 06:40 UTC, DanielJackson-Oslo commented
@mathias234 Denne fikk ikke et bygg, av en eller annen grunn

2021-12-13 13:31 UTC, DanielJackson-Oslo requested changes
To ting jeg gjerne vil ha ordnet her før den går inn i main: 

1) Se om vi kan unngå image.image 

2) Style dette anerledes, med en truncate. 

For #2 så tenker jeg du en fortjener en spec, og at det kan tas i en egen PR om eventuelt jeg kan være lead på. 

Jeg ser for meg at vi har lyst til å gjøre det ganske likt enten AirBNB eller finn. 

AirBNB viser KUN om du har valgt å se bildet stort, og viser da under bildet: 

![image](https://user-images.githubusercontent.com/14905290/145821241-b6758658-38e4-46d6-89dc-85480e2cada1.png)

Finn viser truncated om du ikke har valgt å vise bildet stort, og under bildet om du viser det stort (bildet krymper for å gi plass til underteksten, sånn at den aldri overlapper)

Begge har hvitt-på-svart, i stedet for svart-på-hvitt. 

Jeg har lyst til å eksperimentere litt her i Figma/kode for å se hva som føles rett - og tar gjerne en mini-branch på det. Kan til og med ta den inn til denne, om du vil?

2021-12-13 13:31 UTC, DanielJackson-Oslo commented on app/views/shared/_image_slider.html.erb
> +        <% url = url_for(image.image)  %>
Denne har jeg lyst til å finne en løsning på. Veldig counter-intuitivt og stygt å måtte skrive image.image. 

Bedre da i så fall med image.url, om vi ikke finner en måte å sende den videre til image.image når den ber om path.

2021-12-13 14:43 UTC, mathias234 commented
> 2. Style dette anerledes, med en truncate.

Tror kanskje dette høres ut som en egen PR

2021-12-15 07:40 UTC, DanielJackson-Oslo approved these changes
Virker som en god løsning med .url!

2021-12-15 12:23 UTC, merged