Add safe areas to body
lnu-norge/lokaler.lnu.no pull request #149
Opened 2022-01-21 11:33 UTC by asolvang

Added safe areas to body with env(safe-area-inset...)

To test: 
Use a phone/tablet or similar with a notch.

To run from your computer and being able to see it on mobil run rails s -b 0.0.0.0
On your mobile http://"your-ip":3000/
Example: http://160.1.0.23:3000/

2022-01-21 11:34 UTC, asolvang commented
![](https://github.trello.services/images/mini-trello-icon.png) [Legge opp safe areas for meny og location-boksen på mobil.](https://trello.com/c/XOchiXKU/173-legge-opp-safe-areas-for-meny-og-location-boksen-p%C3%A5-mobil)

2022-01-21 13:54 UTC, mathias234 commented
Hm looks like I am not getting mobile view at all now (happens on my real phone too) I haven't tested locally only on the preview app
![image](https://user-images.githubusercontent.com/2104029/150538734-2cb314c3-ff2b-4213-87ac-171012453b25.png)

2022-01-25 09:57 UTC, DanielJackson-Oslo requested changes
Dessverre umulig å teste atm fordi vi ikke har rett meta viewport. Se kommentar!

Usikker på om vi bare kan slenge alt på body, eller om vi må ha padding-top på menu og litt sånn for å få det pent - men får ikke testet det før viewport-en er på rett sted :)

2022-01-25 09:57 UTC, DanielJackson-Oslo commented on app/views/layouts/application.html.erb
> +    <meta name="viewport" content="viewport-fit=cover" />
Denne overskriver de to over, sånn at de ikke gjelder lenger. Burde kombineres til én, med kommaseparerte verdier:

```html
    <meta name="viewport" content="viewport-fit=cover,width=device-width,initial-scale=1" />
```

Ellers blir det ikke zoomet riktig inn på mobil.

2022-02-02 15:53 UTC, closed without merging

2022-02-02 15:53 UTC, DanielJackson-Oslo commented
After experimenting back and forth for a while, I've realized that Apple does not allow us to show stuff "under the notch" unless in landscape mode anyway, and that this is then such a niche feature that we might as well keep the app as-is for now and come back to it later.