Remember path before login
lnu-norge/lokaler.lnu.no pull request #158
Opened 2022-01-26 16:41 UTC by asolvang

This should save the last location you tried to access as not logged in
If no such location exists it will use default root path

To test:

While not logged in:
Go to localhost:3000/spaces/3
You should now be redirected to login screen
Log in
You should now be redirect to localhost:3000/spaces/3

2022-01-26 16:41 UTC, asolvang commented
![](https://github.trello.services/images/mini-trello-icon.png) [Huske hvor du var når du ble bedt om å logge deg inn, og sende deg dit etter at du har logget inn](https://trello.com/c/mNNchaHo/216-huske-hvor-du-var-n%C3%A5r-du-ble-bedt-om-%C3%A5-logge-deg-inn-og-sende-deg-dit-etter-at-du-har-logget-inn)

2022-02-01 10:20 UTC, DanielJackson-Oslo commented
TIng å sjekke:

- [ ] Fungerer parallel specs fortsatt? Vi fjernet web console fordi den crashet med den
- [ ] Sjekke devise paths
- [ ] Sjekke index paths 
- [ ] Sjekke en space path

2022-02-02 13:51 UTC, DanielJackson-Oslo approved these changes
Klar forbedring fra dagens situasjon!

Følgende er testet og fungerer: 
- [x] Devise paths
- [x] Huske location search OM man er på /spaces
- [x] Huske space path
- [x] Huske admin path
- [x] Parallell tests fungerer fint hos meg 

Følgende fungerer _ikke_, og kan eventuelt fikses i en senere PR (om det ikke er en kjapp fiks) 
- [ ] Huske location search OM man er på / og ikke /spaces

Spesifikt så husker den denne: 
http://localhost:3000/spaces?selectedLocation=59.2232%2C10.9270%2C15.375332684534495&selectedFacilities=Klasserom

men ikke denne: 

http://localhost:3000/?selectedLocation=59.2232%2C10.9270%2C15.375332684534495&selectedFacilities=Klasserom

Selv om begge går til samme sted. 

Mulig riktig løsning er å alltid bruke /spaces ?

2022-02-02 15:48 UTC, mathias234 requested changes
`rake parallel:spec` fungere ikke hos meg, kan være en Linux greie eller noe lokalt hos meg? @asolvang prøv hos deg også
![image](https://user-images.githubusercontent.com/2104029/152187810-5e6b9674-6abf-4f7b-b0c0-4b3d05eab2ab.png)

2022-02-02 15:55 UTC, DanielJackson-Oslo commented
> `rake parallel:spec` fungere ikke hos meg, kan være en Linux greie eller noe lokalt hos meg? @asolvang prøv hos deg også ![image](https://user-images.githubusercontent.com/2104029/152187810-5e6b9674-6abf-4f7b-b0c0-4b3d05eab2ab.png)

Har du prøvd å gjøre som det står på meldingen, og bare flytte det til å være under :development? Kan jo være det fikser det!

2022-02-02 15:57 UTC, asolvang commented
> til

Har aldri brukt parallell specs.

Men kan prøve, virker jo som at dette er en kjent greie for de når de har en melding om det.

Jeg fikser 👍

2022-02-02 16:01 UTC, mathias234 commented
> > til
> 
> Har aldri brukt parallell specs.
> 
> Men kan prøve, virker jo som at dette er en kjent greie for de når de har en melding om det.
> 
> Jeg fikser +1
Yep fant flere andre som har samme problemet på internet også ( beklager force push, var ingen endringer i den var bare i feil branch :D )

2022-02-02 16:03 UTC, mathias234 commented
> Har du prøvd å gjøre som det står på meldingen, og bare flytte det til å være under :development? Kan jo være det fikser det!
Ligger allerede i development, er bare en bug i enten parallel spec eller webconsole som gjør at den laster selv om vi ikke er i dev env

2022-02-02 19:18 UTC, asolvang commented
> > Har du prøvd å gjøre som det står på meldingen, og bare flytte det til å være under :development? Kan jo være det fikser det!
> 
> Ligger allerede i development, er bare en bug i enten parallel spec eller webconsole som gjør at den laster selv om vi ikke er i dev env

Ja så det selv. Fungerte ikke å flytte gemen da den allerede var i dev gruppen.

Skal vi beholde paralell spec eller webconsole?

2022-02-02 19:29 UTC, DanielJackson-Oslo commented
> rake parallel:specs

I readme så står det ikke `rake parallel:spec`, men som under. Når jeg kjører rake paralell:spec så får jeg samme feilmelding som deg, men om jeg kjører som det står i readme så fungerer det hos meg!

Fra Readme: 

> Running in parallel
>  You can run the tests in parallel this will make them faster, this requires you to setup the parallel DB which is done with
>
> `rails parallel:prepare`
> 
> After that you can run the tests with
> 
> `parallel_rspec`

2022-02-02 19:53 UTC, mathias234 commented
> ....

Hm ja ser at parallel_rspec fungerer hos meg også. Skrive rake parallel:spec av vane fra andre prosjekter. Men går greit å bruke parallel_rspec siden dere bruker webconsole

2022-02-04 09:17 UTC, merged