Add devise views to project
lnu-norge/lokaler.lnu.no pull request #31
Opened 2021-10-05 15:10 UTC by asolvang

2021-10-05 15:11 UTC, asolvang commented
![](https://github.trello.services/images/mini-trello-icon.png) [Frontend: Add Devise views](https://trello.com/c/i7HVxKiU/48-frontend-add-devise-views)

2021-10-06 05:37 UTC, DanielJackson-Oslo commented
WIP, obviously, but checked it out now and looks very cool! Looking forward to getting this merged :) 

We have to decide on colours at some point. Currently I've been using a non-LNU pink all over, and it would make sense to standardize on the LNU one - but I haven't prioritzed it yet. I'm thinking I will change the pink-XXX in tailwind for custom pinks generated from LNU pink at some point.

2021-10-06 08:21 UTC, mathias234 requested changes
Looks good, just "one" comment about using inline_svg as we use that for all our other icons

2021-10-06 08:21 UTC, mathias234 commented on app/views/devise/registrations/edit.html.erb
> +          </svg>
See other comment

2021-10-06 08:21 UTC, mathias234 commented on app/views/devise/registrations/new.html.erb
> +            </svg>
See other comment

2021-10-06 08:21 UTC, mathias234 commented on app/views/shared/_notice.html.erb
> +  </svg>
See other comment

2021-10-06 10:59 UTC, asolvang commented
@DanielJackson-Oslo 
> We have to decide on colours at some point. Currently I've...

I setup corlor LNU-> Pink/Blue/Green
Took them from the Logo.

2021-10-06 11:01 UTC, mathias234 approved these changes
LGTM!

2021-10-06 11:57 UTC, merged

2021-10-06 14:20 UTC, DanielJackson-Oslo reviewed
Some comments for posterity and future PRs!

2021-10-06 14:20 UTC, DanielJackson-Oslo commented on app/views/layouts/application.html.erb
> +    <main data-controller="example" class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
data-controller="example" seems a bit weird! Left over from some other code?

2021-10-06 14:20 UTC, DanielJackson-Oslo commented on app/views/devise/registrations/new.html.erb
> +      <%= image_tag 'logo.svg', alt: 'LNU logo', width: 200, height: 200, class: 'mx-auto h-12 w-auto' %>
This code is duplicated between views registrations/new and sessions/new. Should be pulled out to it's own little thing?