Add a button for location search
lnu-norge/lokaler.lnu.no pull request #97
Opened 2021-11-22 12:34 UTC by mathias234

Added a button to the new searchbox for going to current location
![image](https://user-images.githubusercontent.com/2104029/142862579-ac9f4f8a-f1cb-4548-8043-8ecedb13f3fb.png)

2021-11-22 13:03 UTC, DanielJackson-Oslo requested changes
Fin løsning!

To kommentarer: 

- Kan vi ikke bare kjøre flyTo, i stedet for initialize, i alle fall om vi allerede har kartet oppe? Se egen kommentar og loom.
- På mobil ser det ikke ut til å fungere hos meg, uten at jeg helt hvet hvorfor, får bare sånn her: 

![image](https://user-images.githubusercontent.com/14905290/142865264-42c2f5f2-0dad-4cfc-879f-d7e6302e31de.png)

Jeg kan ha sagt nei til lokasjon tidligere, men selv etter å ha fulgt oppskriften gitt i kommentarfeltet her så fungerer det ikke. Fungerer det hos deg? I så fall er et nok bare telefonen min som kødder det til. 

https://stackoverflow.com/questions/10422322/location-services-in-mobile-safari-dont-allow-is-saved-forever-even-with-re

2021-11-22 13:09 UTC, mathias234 commented on app/javascript/controllers/mapbox_controller.js
> +        center: [position.coords.longitude, position.coords.latitude],
Yepp god ide

2021-11-22 13:40 UTC, DanielJackson-Oslo approved these changes
Ser bra ut!

En bekymring jeg har, som kan tas i en egen PR, er at vi nå har et lite felt rundt knappen som ikke kan trykkes på, men som allikevel lights up på :hover. 

Det skjer fordi "py-3 px-4 " er satt på span-en, og ikke på knappene. Å flytte den til knappene( men da kompensere med å sette pr-4 og pl-4 i stedet for px-4 så det bare er ytterkantene) kan være riktig! Kan også være vi vil kompensere for border og ta det inn i knappene, men usikker på om den får :hover på border også.

2021-11-24 08:07 UTC, mathias234 commented
@DanielJackson-Oslo fikset litt på borders men må bli bedre enda, merger sånn det er nå så kan vi ta resten i en egen PR

2021-11-24 08:09 UTC, merged